import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from './ui/header'



const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="eng">  
      <body className={`${inter.className} top-0 antialiased bg-white`  }>       
       <Header />
        {children}
      
         </body>
    </html>
    
  )
}